#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'camera','console_scripts','line_detector_follower_node'
__requires__ = 'camera'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('camera', 'console_scripts', 'line_detector_follower_node')()
    )
